# data_management.py

import os
import pandas as pd
import numpy as np

def create_data_collector():
    """Return a fresh data dictionary for trial information.

    The returned structure keeps lists for each field so that values from
    every trial can be appended sequentially during the experiment.

    Keys
    ----
    trial_number : list[int]
        1‑based index of each trial.
    stimulus_temp : list[float]
        Temperature presented for the trial in degrees Celsius.
    selected_surface : list[int]
        Thermode surface used for the stimulation.
    pain_binary_coded : list[int]
        Participant pain report, ``1`` for painful and ``0`` for non‑painful.
    vas_final_coded_rating : list[float]
        Final VAS rating coded with the context offset (100 for painful trials).
    vas_traces : list[list[float]]
        Sequence of sampled VAS ratings throughout the trial.
    vas_times : list[list[float]]
        Time stamps for each rating sample in seconds from VAS onset.
    iti_start_time : list[float]
        Absolute clock time when the inter-trial interval began.
    iti_end_time : list[float]
        Absolute clock time when the inter-trial interval ended.
    stim_start_time : list[float]
        Time when stimulation onset occurred.
    stim_end_time : list[float]
        Time when stimulation ended.
    pain_q_start_time : list[float]
        Timestamp for the start of the pain question routine.
    pain_q_end_time : list[float]
        Timestamp for the end of the pain question routine.
    vas_start_time : list[float]
        Timestamp for the start of the VAS rating routine.
    vas_end_time : list[float]
        Timestamp for the end of the VAS rating routine.
    """
    return {
        'trial_number': [],
        'stimulus_temp': [],
        'selected_surface': [],
        'pain_binary_coded': [],
        'vas_final_coded_rating': [],
        'vas_traces': [],
        'vas_times': [],
        'iti_start_time': [],
        'iti_end_time': [],
        'stim_start_time': [],
        'stim_end_time': [],
        'pain_q_start_time': [],
        'pain_q_end_time': [],
        'vas_start_time': [],
        'vas_end_time': []
    }

def save_all_data(exp_info, exp_name, data, this_dir):
    """Write experiment data to disk in multiple convenient formats.

    Parameters
    ----------
    exp_info : dict
        Dictionary returned by the PsychoPy dialog containing participant
        and session information.
    exp_name : str
        Short experiment name used in file naming.
    data : dict
        Structure generated by :func:`create_data_collector` holding all trial
        lists.
    this_dir : str
        Base directory where the ``data`` folder will be created if needed.

    Three files are produced inside ``data/<participant_id>``:

    ``<id>_<exp>_<date>_TrialSummary.csv``
        One row per trial with key outcome measures.
    ``<id>_<exp>_<date>_VASTraces_Long.csv``
        Long-format file of sampled VAS ratings for every trial.
    ``<id>_<exp>_<date>_BACKUP.npz``
        Numpy compressed archive of the raw collector dictionary for any custom
        post-processing.
    """
    participant_id = str(exp_info.get('participant', 'UNKNOWN'))
    date_str = str(exp_info.get('date', 'NODATE'))
    
    # Create output directory
    participant_dir = os.path.join(this_dir, 'data', participant_id)
    os.makedirs(participant_dir, exist_ok=True)
    
    base_filename = f"{participant_id}_{exp_name}_{date_str}"

    # --- Save Trial Summary CSV ---
    try:
        summary_df = pd.DataFrame({
            'trial_number': data['trial_number'],
            'stimulus_temp': data['stimulus_temp'],
            'selected_surface': data['selected_surface'],
            'pain_binary_coded': data['pain_binary_coded'],
            'vas_final_coded_rating': data['vas_final_coded_rating'],
            'iti_start_time': data['iti_start_time'],
            'iti_end_time': data['iti_end_time'],
            'stim_start_time': data['stim_start_time'],
            'stim_end_time': data['stim_end_time'],
            'pain_q_start_time': data['pain_q_start_time'],
            'pain_q_end_time': data['pain_q_end_time'],
            'vas_start_time': data['vas_start_time'],
            'vas_end_time': data['vas_end_time']
        })
        summary_filename = os.path.join(participant_dir, f"{base_filename}_TrialSummary.csv")
        summary_df.to_csv(summary_filename, index=False, float_format='%.2f', na_rep='NA')
        print(f"Trial summary saved to {summary_filename}")
    except Exception as e:
        print(f"ERROR saving summary CSV: {e}")

    # --- Save VAS Traces Long Format CSV ---
    try:
        vas_long_list = []
        for i in range(len(data['trial_number'])):
            for sample_idx, (rating, time) in enumerate(zip(data['vas_traces'][i], data['vas_times'][i])):
                vas_long_list.append({
                    'participant_id': participant_id,
                    'trial_number': data['trial_number'][i],
                    'stimulus_temp': data['stimulus_temp'][i],
                    'pain_context_0no_1yes': data['pain_binary_coded'][i],
                    'sample_in_trace': sample_idx + 1,
                    'vas_time_in_trial_secs': time,
                    'vas_coded_rating': rating
                })
        if vas_long_list:
            vas_df = pd.DataFrame(vas_long_list)
            vas_filename = os.path.join(participant_dir, f"{base_filename}_VASTraces_Long.csv")
            vas_df.to_csv(vas_filename, index=False, float_format='%.4f', na_rep='NA')
            print(f"VAS traces saved to {vas_filename}")
    except Exception as e:
        print(f"ERROR saving VAS traces CSV: {e}")

    # --- Save Raw Lists Backup ---
    try:
        backup_filename = os.path.join(participant_dir, f"{base_filename}_BACKUP.npz")
        # Use dtype=object for lists of lists/uneven arrays
        np.savez_compressed(backup_filename, **{k: np.array(v, dtype=object) for k, v in data.items()})
        print(f"Raw data backup saved to {backup_filename}")
    except Exception as e:
        print(f"ERROR saving raw backup: {e}")
